site_name: Unreal Engine Plugins
dev_addr: 0.0.0.0:8000
theme:
  palette:
    scheme: default
  name: material
  features:
    - navigation.top
    - navigation.tracking
    - header.autohide
    - navigation.instant
    - navigation.expand
    - search.suggest
    - search.share
    - navigation.footer
    - navigation.sections
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.tabs
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.prune
    - toc.integrate
    - content.tabs.link
nav:
  - Plugins: ./index.md
  - Snap Central:
      - Introduction: ./snap-central/index.md
      - Possible Use Cases: ./snap-central/use-cases.md
      - Setup: ./snap-central/setup.md
      - The Grid Actor: ./snap-central/the-grid.md
      - The Function:
          - Basic Usage: ./snap-central/usage.md
          - Example: ./snap-central/example.md
          - Input Parameters: ./snap-central/input-parameters.md
          - Output Parameters: ./snap-central/output-parameters.md
      - Runtime Controls: ./snap-central/runtime-controls.md
      - Epilogue: ./snap-central/epilogue.md
      - FAQ: ./snap-central/faq.md
      - Changelog: ./snap-central/changelog.md
  - Trail Blazer:
     - Introduction: ./trail-blazer/index.md
     - Possible Use Cases: ./trail-blazer/use-cases.md
     - Examples: ./trail-blazer/examples.md
     - The Actor: ./trail-blazer/the-actor.md
     - Usage: ./trail-blazer/usage.md
     - Epilog: ./trail-blazer/epilogue.md
     - FAQ: ./trail-blazer/faq.md
  - Aero Sim:
     - Introduction: ./aero-sim/index.md
     - Possible Use Cases: ./aero-sim/use-cases.md
     - Atmosphere Actor: ./aero-sim/atmosphere.md
     - Influence Actors: ./aero-sim/influencers.md
     - Gas Types: ./aero-sim/gases.md
     - Nodes: ./aero-sim/nodes.md
     - Measurement: ./aero-sim/measurement.md
     - Usage: ./aero-sim/usage.md
     - Visuals: ./aero-sim/visuals.md
     - Epilog: ./aero-sim/epilogue.md
     - FAQ: ./aero-sim/faq.md
  # - Flux Point:
  #    - Introduction: ./flux-point/index.md
  #    - Shapes: ./flux-point/index.md
plugins:
  - search
  - glightbox
extra_css:
  - assets/stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: True
extra:
  generator: false
