site_name: Snap Central - Documentation
dev_addr: 0.0.0.0:8000
theme:
  name: material
  features:
    - navigation.tracking
    - header.autohide
    - navigation.instant
    - navigation.expand
    - search.suggest
    - search.share
    - navigation.footer
    - navigation.sections
    - toc.integrate
nav:
  - Introduction: ./index.md
  - Possible Use Cases: ./use-cases.md
  - Setup: ./setup.md
  - The Grid Actor: ./the-grid.md
  - The Function:
      - Basic Usage: ./usage.md
      - Example: ./example.md
      - Input Parameters: ./input-parameters.md
      - Output Parameters: ./output-parameters.md
  - FAQ: ./faq.md
  - Epilogue: ./epilogue.md
plugins:
  - search
  - glightbox
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: True
extra:
  generator: false
